# Generated by Django 2.0.7 on 2018-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impactfactor',
            fields=[
                ('impactfactor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('impactfactor_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'impactfactor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('journal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('professor_id', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('professor_homepage', models.CharField(blank=True, max_length=45, null=True)),
                ('depart_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('scholar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scholar_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scholar',
                'managed': False,
            },
        ),
    ]
